apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: compose-gateway
  namespace: {{ .Values.namespace }}
spec:
  gatewayClassName: nginx
  listeners:
  - name: http-frontend
    port: 80
    protocol: HTTP
    hostname: {{ .Values.portal.baseUrl }}
  - name: http-backend
    port: 80
    protocol: HTTP
    hostname: {{ .Values.scaas.baseUrl }}
  - name: https-frontend
    port: 443
    protocol: HTTPS
    hostname: {{ .Values.portal.baseUrl }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: frontend-tls-secrets
  - name: https-backend
    port: 443
    protocol: HTTPS
    hostname: {{ .Values.scaas.baseUrl }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: backend-tls-secrets
