apiVersion: v1
kind: Secret
metadata:
  name: frontend-tls-secrets
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.frontend.crt | b64enc }}
  tls.key: {{ .Values.tls.frontend.key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-tls-secrets
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.backend.crt | b64enc }}
  tls.key: {{ .Values.tls.backend.key | b64enc }}
