apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-tls-redirect
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: compose-gateway
    sectionName: http-frontend
  hostnames:
  - {{ .Values.portal.baseUrl }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-tls-redirect
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: compose-gateway
    sectionName: http-backend
  hostnames:
  - {{ .Values.scaas.baseUrl }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: compose-gateway
    sectionName: https-frontend
  hostnames:
  - {{ .Values.portal.baseUrl }}
  rules:
  - backendRefs:
    - name: portal
      port: {{ .Values.portal.containerPort }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: compose-gateway
    sectionName: https-backend
  hostnames:
  - {{ .Values.scaas.baseUrl }}
  rules:
  - backendRefs:
    - name: scaas
      port: {{ .Values.scaas.containerPort }}
