apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.portal.replicaCount }}
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal
        image: {{ .Values.portal.image }}
        args:
        - "npm"
        - "start"
        env:
        - name: VIRTUAL_PORT
          value: {{ .Values.portal.containerPort | quote }}
        - name: VIRTUAL_HOST
          value: {{ .Values.portal.baseUrl | quote }}
        - name: LETSENCRYPT_HOST
          value: {{ .Values.portal.baseUrl | quote }}
        - name: NODE_ENV
          value: "production"
        - name: SERVER_PORT
          value: {{ .Values.portal.containerPort | quote }}
        - name: SCAAS_URL
          value: "http://scaas:{{ .Values.scaas.containerPort }}"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: portal-secrets
              key: jwt-secret
        ports:
        - containerPort: {{ .Values.portal.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.portal.containerPort }}
    targetPort: {{ .Values.portal.containerPort }}
  selector:
    app: portal
