apiVersion: v1
kind: Secret
metadata:
  name: scaas-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  secret-key: {{ .Values.scaas.secretKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: portal-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.portal.jwtSecret | quote }}
