# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- project: to-be-continuous/node
  ref: '3.6'
  file: /templates/gitlab-ci-node.yml
- project: to-be-continuous/sonar
  ref: '4.2.3'
  file: /templates/gitlab-ci-sonar.yml
- template: Security/Secret-Detection.gitlab-ci.yml

variables:
  NODE_OPTIONS: "--openssl-legacy-provider"
  NODE_LINT_ENABLED: 'true'
  NODE_AUDIT_DISABLED: 'true'
  NODE_OUTDATED_DISABLED: 'true'
  NODE_SBOM_DISABLED: 'true'
  SONAR_BASE_ARGS: "-X"
  SONAR_HOST_URL: https://sqaas.dos.tech.orange

docker_build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint:
    - ''
  script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}"
    "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  - '/kaniko/executor --context "${CI_PROJECT_DIR}"       --dockerfile "${CI_PROJECT_DIR}/Dockerfile"       --destination
    "${CI_REGISTRY_IMAGE}:dev"'

publish-qualif:
  stage: publish
  image: dockerproxy.repos.tech.orange/docker:25-dind
  services:
  - name: dockerproxy.repos.tech.orange/docker:25-dind
    alias: docker
  tags:
  - graas-dind
  before_script:
  - command -v ssh-agent >/dev/null || ( apk add --update openssh )
  - eval $(ssh-agent -s)
  - echo "$SSH_QUALIF_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $QUALIF_IPADDRESS >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker pull $CI_REGISTRY_IMAGE:dev
  - docker save -o portal.tar $CI_REGISTRY_IMAGE:dev
  - ls -a .
  - scp portal.tar $SSH_QUALIF_USER@$QUALIF_IPADDRESS:images/portal.tar
  dependencies:
  - docker_build

stages:
- build
- test
- package-build
- package-test
- infra
- deploy
- acceptance
- publish
- infra-prod
- production
